# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
      - area/dependencies
    ignore:
      # explicitly keep baseline version
      - dependency-name: jakarta.platform:*
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: net.revelc.code.formatter:formatter-maven-plugin
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: net.revelc.code:impsort-maven-plugin
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # explicitly keep baseline version
      - dependency-name: org.jboss.weld.*:*
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    rebase-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - area/infra
    rebase-strategy: auto
