_extends: .github
name-template: 'CDI-Unit $RESOLVED_VERSION'
tag-template: 'cdi-unit-$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'area/infra'
      - 'chore'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'area/dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'semver/major'
  minor:
    labels:
      - bug
      - enhancement
      - feature
      - 'semver/minor'
  patch:
    labels:
      - performance
      - 'semver/patch'
  default: patch
template: |
  ## Changes

  $CHANGES
