_extends: .github
name-template: 'CDI-Unit $RESOLVED_VERSION'
tag-template: 'cdi-unit-$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/fix'
      - 'kind/bugfix'
      - 'kind/bug'
  - title: '🧰 Maintenance'
    labels:
      - 'area/infra'
      - 'kind/chore'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'area/dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'semver/major'
  minor:
    labels:
      - 'kind/bug'
      - 'kind/enhancement'
      - 'kind/feature'
      - 'semver/minor'
  patch:
    labels:
      - 'kind/performance'
      - 'semver/patch'
  default: patch
template: |
  ## Changes

  $CHANGES
