name: Build and Test with Eclipse Temurin JDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Cache build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Download Dependencies
        run: ./mvnw -V clean verify -Dmaven.main.skip -Dmaven.test.skip --quiet --batch-mode

      - name: Build with Maven
        run: ./ci-support/build.sh

  test-weld:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]
        weld:
          - v1.1
          - v2.0
          - v2.1
          - v2.2
          - v2.3
          - v2.4
          - v3.0
          - v3.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Restore build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-
            ${{ env.cache-name }}-${{ github.sha }}-

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test Weld ${{ matrix.weld }}
        run: ./ci-support/test-weld.sh weld-${{ matrix.weld }}.sh

  test-deltaspike:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Restore build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-
            ${{ env.cache-name }}-${{ github.sha }}-

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test DeltaSpike
        run: ./ci-support/test-deltaspike.sh deltaspike-v1.x.sh
