name: Build and Test with Zulu JDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'maven'

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Cache build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Download Dependencies
        run: ./mvnw -V clean verify -Dmaven.main.skip -Dmaven.test.skip --quiet --batch-mode

      - name: Build with Maven
        run: ./ci-support/build.sh

  test-weld:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # LTS versions
        java: [11, 17, 21]
        weld:
          - v4.0
          - v5.0
          - v5.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'

      - name: Restore build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-
            ${{ env.cache-name }}-${{ github.sha }}-

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test Weld ${{ matrix.weld }}
        run: ./ci-support/test-weld.sh weld-${{ matrix.weld }}.sh

  test-deltaspike:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # LTS versions
        java: [11, 17, 21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'

      - name: Restore build artifacts
        uses: actions/cache@v2
        env:
          cache-name: build-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.sha }}-${{ github.run_id }}-
            ${{ env.cache-name }}-${{ github.sha }}-

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test DeltaSpike
        run: ./ci-support/test-deltaspike.sh deltaspike-v2.x.sh
