name: Build and Test with Zulu JDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Download Dependencies
        run: ./mvnw -V clean verify -Dmaven.main.skip -Dmaven.test.skip --quiet --batch-mode

      - name: Build with Maven
        run: ./ci-support/build.sh

      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

  test-weld:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]
        weld:
          - v1.1
          - v2.0
          - v2.1
          - v2.2
          - v2.3
          - v2.4
          - v3.0
          - v3.1

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test Weld ${{ matrix.weld }}
        run: ./ci-support/test-weld.sh weld-${{ matrix.weld }}.sh

  test-deltaspike:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - uses: s4u/maven-settings-action@v2.3.0
        with:
          mirrors: '[{
            "id": "google-maven-central",
            "name": "GCS Maven Central mirror EU",
            "mirrorOf": "central",
            "url": "https://maven-central-eu.storage-download.googleapis.com/maven2/"
          }]'

      - name: Test DeltaSpike
        run: ./ci-support/test-deltaspike.sh deltaspike-v1.x.sh
