name: Release to Maven Central

on:
  pull_request:
    types:
      - closed
    paths:
      - '.github/project.yml'

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  MAVEN_DEPLOY_USERNAME: ${{secrets.MAVEN_DEPLOY_USERNAME}}
  MAVEN_DEPLOY_TOKEN: ${{secrets.MAVEN_DEPLOY_TOKEN}}
  MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}
  MAVEN_ARGS: "-V -B --settings .github/mvn-settings.xml --no-transfer-progress"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Retrieve project metadata
        id: metadata
        uses: radcortez/project-metadata-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: true

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        env:
          GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}
        with:
          java-version: 17
          distribution: 'temurin'
          gpg-private-key: ${{secrets.MAVEN_GPG_PRIVATE_KEY}}

      - name: Prepare Release for ${{steps.metadata.outputs.current-version}}
        env:
          MAVEN_RELEASE_ARGS: "-DautoVersionSubmodules -DpushChanges=false -DlocalCheckout -DreleaseVersion=${{steps.metadata.outputs.current-version}} -Dtag=cdi-unit-${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}"
        run: |
          java -version
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b release
          ./mvnw release:prepare ${{env.MAVEN_RELEASE_ARGS}}

      - name: Perform Release for ${{steps.metadata.outputs.current-version}}
        run: |
          git checkout ${{github.base_ref}}
          git rebase release
          ./mvnw release:perform
          git push --force --set-upstream origin release

      - name: Push Tags for ${{steps.metadata.outputs.current-version}}
        run: |
          git push --tags

      - name: Upload relocations
        uses: actions/upload-artifact@v5
        with:
          name: cdi-unit-relocations-${{steps.metadata.outputs.current-version}}
          path: relocations/**/target/*
          retention-days: 7
